export const SCREENS = {
  QIZ_BOX_HOME_SCREEN: 'QIZ_BOX_HOME_SCREEN',
  QIZ_BOX_START_QUIZ_SCREEN: 'QIZ_BOX_START_QUIZ_SCREEN',
  QIZ_BOX_PLAY_QUIZ_SCREEN: 'QIZ_BOX_PLAY_QUIZ_SCREEN',
  QIZ_BOX_QUIZ_RESULT_SCREEN: 'QIZ_BOX_QUIZ_RESULT_SCREEN',
};
